services:
  mongo:
    image: mongo:latest
    container_name: rubypome_mongo
    networks:
      - rubypome

  server:
    build:
      context: ./server/
      dockerfile: Dockerfile
    container_name: rubypome_server
    env_file:
      - ./server/.env
    environment:
      - DB_HOST=rubypome_mongo
      - DB_PORT=27017
    networks:
      - rubypome

  client:
    build:
      context: ./client/
      dockerfile: Dockerfile
    container_name: rubypome_client
    env_file:
      - ./client/.env
    ports:
      - '5173:5173'
    networks:
      - rubypome

  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    image: rubypome_nginx
    container_name: rubypome_nginx
    ports:
      - 8001:80
    volumes:
      - ./:/var/www
    networks:
      - rubypome

networks:
  rubypome:
    driver: bridge
